language: android
sudo: required
jdk: oraclejdk17

branches:
  only:
    - development
    - uat
    - master

env:
  global:
    - ANDROID_API_LEVEL=34
    - ANDROID_BUILD_TOOLS_VERSION=34.0.0
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools
    - cmdline-tools;latest
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extras;google;auto
    - extras;android;m2repository
    - extras;google;m2repository
    - sources;android-$ANDROID_BUILD_TOOLS_VERSION
    - system-images;android-$ANDROID_API_LEVEL;
    - platforms;android-$ANDROID_BUILD_TOOLS_VERSION

before_install:
  - yes | sdkmanager --install "cmdline-tools;latest"
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
  - chmod +x ./gradlew

script:
  - ./gradlew lint
  - ./gradlew testDebugUnitTest
  # Build debug on development or uat branch
  - if [ "$TRAVIS_BRANCH" = "development" ] || [ "$TRAVIS_BRANCH" = "uat" ]; then
    ./gradlew assembleDebug;
    fi
  # Build release on master branch
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    ./gradlew assembleRelease;
    fi

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
